"""Full-corpus ASBX block-size sweep for the SPE artefact.

Outputs
-------
  SPE/results/block_size_sweep.csv
  SPE/results/block_size_sweep_summary.csv
  SPE/LDA_Stego_ASBX/tables/tab_block_size_sweep.tex
"""

from __future__ import annotations

import csv
import statistics
import sys
from collections import defaultdict
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parents[1]
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_REPO_ROOT / "experiments" / "src"))

from asbc import decode, encode_deterministic  # noqa: E402
from software_benchmark import payloads  # noqa: E402

_RESULTS_DIR = _HERE.parent / "results"
_TABLES_DIR = _HERE.parent / "LDA_Stego_ASBX" / "tables"
BLOCK_SIZES = [32, 64, 128, 256, 512, 1024, 2048]


def run() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    corpus = payloads()
    print(f"Loaded {len(corpus)} payloads for block-size sweep.")
    for domain, name, data in corpus:
        for block_size in BLOCK_SIZES:
            encoded = encode_deterministic(data, block_size=block_size)
            recovered = decode(encoded)
            rows.append(
                {
                    "domain": domain,
                    "payload": name,
                    "input_bytes": len(data),
                    "block_size": block_size,
                    "encoded_bytes": len(encoded),
                    "ratio": round(len(encoded) / len(data), 6),
                    "round_trip_ok": recovered == data,
                }
            )
        print(f"  {domain:14s} {name:28s} swept")
    return rows


def write_outputs(rows: list[dict[str, object]]) -> None:
    _RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    _TABLES_DIR.mkdir(parents=True, exist_ok=True)

    with (_RESULTS_DIR / "block_size_sweep.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    by_domain_size: dict[tuple[str, int], list[float]] = defaultdict(list)
    by_domain: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        by_domain_size[(str(row["domain"]), int(row["block_size"]))].append(float(row["ratio"]))
        by_domain[str(row["domain"])].append(row)

    summary: list[dict[str, object]] = []
    for domain in sorted(by_domain):
        medians = {
            block_size: statistics.median(by_domain_size[(domain, block_size)])
            for block_size in BLOCK_SIZES
        }
        best_block = min(medians, key=lambda size: (medians[size], size))
        ratio_256 = medians[256]
        best_ratio = medians[best_block]
        summary.append(
            {
                "domain": domain,
                "n_payloads": len({str(row["payload"]) for row in by_domain[domain]}),
                "best_block_size": best_block,
                "best_median_ratio": round(best_ratio, 6),
                "median_ratio_256": round(ratio_256, 6),
                "relative_gain_vs_256_percent": round(100.0 * (ratio_256 - best_ratio) / max(ratio_256, 1e-12), 3),
                "all_round_trips_ok": all(bool(row["round_trip_ok"]) for row in by_domain[domain]),
            }
        )

    with (_RESULTS_DIR / "block_size_sweep_summary.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(summary[0]))
        writer.writeheader()
        writer.writerows(summary)

    labels = {
        "sparse_matrix": "Sparse matrices",
        "image_tensor": "Image tensors",
        "text_control": "Text controls",
        "mixed_control": "Mixed controls",
        "synthetic": "Synthetic",
    }
    order = ["sparse_matrix", "image_tensor", "text_control", "mixed_control", "synthetic"]
    lookup = {str(row["domain"]): row for row in summary}
    lines = [
        "% Generated by SPE/code/block_size_sweep.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Full-corpus ASBX deterministic block-size sweep. Ratios are medians over payloads in each domain; lower is better.}",
        "\\label{tab:block-size-sweep}",
        "\\small",
        "\\begin{tabular}{@{}lrrrr@{}}",
        "\\toprule",
        "Domain & $n$ & Best $b$ & Best $R$ & Gain vs. $b=256$ \\\\",
        "\\midrule",
    ]
    for domain in order:
        row = lookup.get(domain)
        if row is None:
            continue
        lines.append(
            f"{labels[domain]} & {row['n_payloads']} & {row['best_block_size']} & "
            f"{float(row['best_median_ratio']):.3f} & "
            f"{float(row['relative_gain_vs_256_percent']):.1f}\\% \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    (_TABLES_DIR / "tab_block_size_sweep.tex").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = run()
    if not rows:
        raise SystemExit("no rows generated")
    if not all(bool(row["round_trip_ok"]) for row in rows):
        raise SystemExit("round-trip failure in block-size sweep")
    write_outputs(rows)
    print("Block-size sweep complete.")


if __name__ == "__main__":
    main()
